version: '3'
services:
  app:
    build: ./app
    stop_signal: SIGKILL
    restart: on-failure
    command: gunicorn app:app -c gunicorn.py --preload --log-config ./config/logger.conf
    environment:
      - SERVER_PORT:5000
    ports:
      - 5000:5000
      - 80:80
    depends_on:
      - fluentd
    volumes:
      - ./app/app.py:/var/server/app.py
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: gunicorn.access

  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    expose:
      - 9200
    environment:
      - discovery.type=single-node # Runs as a single-node
      - xpack.security.enabled=false
    volumes: # Stores elasticsearch data locally on the esdata Docker volume
      - esdata:/usr/share/elasticsearch/data

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links: # Sends incoming logs to the elasticsearch container.
      - elasticsearch
    depends_on:
      - elasticsearch
    ports: # Exposes the port 24224 on both TCP and UDP protocol for log aggregation
      - 24224:24224
      - 24224:24224/udp

  kibana:
    image: kibana:8.7.1
    container_name: kibana
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment: # Defined host configuration
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

# Define the Docker volume named esdata for the Elasticsearch container.
volumes:
  esdata:
